import StringInstrument from "./StringInstrument";

class instrumentName extends StringInstrument{
  tuning = [];
  amntFrets = 0;
  chordPosition = {
    C:{
      Major: [],
      Augmented: [],
      Major_Sixth:[],
      Major_Seventh:[],
      Major_Ninth:[],
      Minor: [],
      Diminished: [],
      Minor_Sixth: [],
      Minor_Seventh: [],
      Minor_Ninth: [],
      Sus2: [],
      Sus4: [],
    },
    C_Sharp:{
      Major: [], 
      Augmented: [],
      Major_Sixth:[],
      Major_Seventh:[],
      Major_Ninth:[],
      Minor: [],
      Diminished: [],
      Minor_Sixth: [],
      Minor_Seventh: [],
      Minor_Ninth: [],
      Sus2: [],
      Sus4: [],
    },
    D:{
      Major: [],
      Augmented: [],
      Major_Sixth:[],
      Major_Seventh:[],
      Major_Ninth:[],
      Minor: [],
      Diminished: [],
      Minor_Sixth: [],
      Minor_Seventh: [],
      Minor_Ninth: [],
      Sus2: [],
      Sus4: [],
    },
    D_Sharp:{
      Major: [],
      Augmented: [],
      Major_Sixth:[],
      Major_Seventh:[],
      Major_Ninth:[],
      Minor: [],
      Diminished: [],
      Minor_Sixth: [],
      Minor_Seventh: [],
      Minor_Ninth: [],
      Sus2: [],
      Sus4: [],
    },
    E:{
      Major: [],
      Augmented: [],
      Major_Sixth:[],
      Major_Seventh:[],
      Major_Ninth:[],
      Minor: [],
      Diminished: [],
      Minor_Sixth: [],
      Minor_Seventh: [],
      Minor_Ninth: [],
      Sus2: [],
      Sus4: [],
    },
    F:{
      Major: [],
      Augmented: [],
      Major_Sixth:[],
      Major_Seventh:[],
      Major_Ninth:[],
      Minor: [],
      Diminished: [],
      Minor_Sixth: [],
      Minor_Seventh: [],
      Minor_Ninth: [],
      Sus2: [],
      Sus4: [],
    },
    F_Sharp:{
      Major: [],
      Augmented: [],
      Major_Sixth:[],
      Major_Seventh:[],
      Major_Ninth:[],
      Minor: [],
      Diminished: [],
      Minor_Sixth: [],
      Minor_Seventh: [],
      Minor_Ninth: [],
      Sus2: [],
      Sus4: [],
    },
    G:{
      Major: [],
      Augmented: [],
      Major_Sixth:[],
      Major_Seventh:[],
      Major_Ninth:[],
      Minor: [],
      Diminished: [],
      Minor_Sixth: [],
      Minor_Seventh: [],
      Minor_Ninth: [],
      Sus2: [],
      Sus4: [],
    },
    G_Sharp:{
      Major: [],
      Augmented: [],
      Major_Sixth:[],
      Major_Seventh:[],
      Major_Ninth:[],
      Minor: [],
      Diminished: [],
      Minor_Sixth: [],
      Minor_Seventh: [],
      Minor_Ninth: [],
      Sus2: [],
      Sus4: [],
    },
    A:{
      Major: [],
      Augmented: [],
      Major_Sixth:[],
      Major_Seventh:[],
      Major_Ninth:[],
      Minor: [],
      Diminished: [],
      Minor_Sixth: [],
      Minor_Seventh: [],
      Minor_Ninth: [],
      Sus2: [],
      Sus4: [],
    },
    A_Sharp:{
      Major: [],
      Augmented: [],
      Major_Sixth:[],
      Major_Seventh:[],
      Major_Ninth:[],
      Minor: [],
      Diminished: [],
      Minor_Sixth: [],
      Minor_Seventh: [],
      Minor_Ninth: [],
      Sus2: [],
      Sus4: [],
    },
    B:{
      Major: [],
      Augmented: [],
      Major_Sixth:[],
      Major_Seventh:[],
      Major_Ninth:[],
      Minor: [], //[[2, 4], [2], [2], [2]] or [[2, 4], 2, 2, 2]
      Diminished: [],
      Minor_Sixth: [],
      Minor_Seventh: [],
      Minor_Ninth: [],
      Sus2: [],
      Sus4: [],
    },
  }
}